mybatis-plus:
  mapper-locations: classpath:com.yumsxi.admin.mbutil/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial #图对所有的属性执行自动映射
    map-underscore-to-camel-case: true # 将带有下划线的表字段映射为驼峰格式的实体类属性