spring:
  datasource:
    url: jdbc:mysql://192.168.1.104:3306/vote?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: SuperK2018

  mail:
    host: smtp.qq.com
    username: 2778686329@qq.com
    password: umyrvuswkroudfij
    default-encoding: UTF-8
    protocol: smtp

  redis:
    host: 192.168.1.104 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: yumsximin3570844 # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com.vote: debug


